### ISSUE TITLE
404 error - page not found in master branch for Structured-data-and-lists.md

### ISSUE THREAD

**Issue by jambelien** [MIABIS/miabis#53]
Please update master branch for page https://github.com/BBMRI-ERIC/miabis/blob/master/Structured-data-and-lists.md 

Note that the two patches: 1) https://github.com/BBMRI-ERIC/miabis/blob/CeciliaEngels-patch-1/Structured-data-and-lists.md and 2) https://github.com/BBMRI-ERIC/miabis/blob/CeciliaEngels-patch-2/Structured-data-and-lists.md, do have a valid page.

**Comment by niinae** [comment]
Thank you for filing this issue. We are currently in the middle of restructuring the different lists in MIABIS Github (Entire list of attributes and structured data and [value] lists) to make them more informative and understandable, and hoping to get the updates done within this month. For the time being, you can find the page you are looking for here https://github.com/BBMRI-ERIC/miabis/tree/master/draft/all%20attributes%20%2B%20structured%20data%20%2B%20lists%20, and after the revamping and pending updates it is going to be shifted under the master branch.

Can I merge this issue with #52 because they are related?

**Comment by jambelien** [comment]
> Thank you for filing this issue. We are currently in the middle of restructuring the different lists in MIABIS Github (Entire list of attributes and structured data and [value] lists) to make them more informative and understandable, and hoping to get the updates done within this month. For the time being, you can find the page you are looking for here https://github.com/BBMRI-ERIC/miabis/tree/master/draft/all%20attributes%20%2B%20structured%20data%20%2B%20lists%20, and after the revamping and pending updates it is going to be shifted under the master branch.
> 
> Can I merge this issue with #52 because they are related?

Yes, please merge

**Comment by niinae** [comment]
Closed being closely related to #52

**Comment by niinae** [comment]
Structured data are now updated and made available in  https://github.com/BBMRI-ERIC/miabis/blob/master/all%20structured%20data.md. Link is also fixed in master/Readme.md

Tables to present enumerated valuelists and their definitions are still in preparation.
